# Generated by Django 4.1.5 on 2023-01-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='')),
                ('slug', models.SlugField()),
                ('content', models.TextField()),
                ('preview', models.ImageField(upload_to='blog/', verbose_name='')),
                ('is_published', models.BooleanField(default=False, verbose_name='')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
    ]
