# Generated by Django 4.2.2 on 2023-06-14 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='description',
        ),
    ]
